#!/bin/sh
set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

export PATH=/usr/local/bin:${PATH}

. $(dirname $0)/common.sh
serverless_cmd info

jq -n "{
  version: {

  },
  metadata: [

  ]
}" >&3
