#!/bin/sh
set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

. $(dirname $0)/common.sh

export PATH=/usr/local/bin:${PATH}

store_payload

cmd="deploy"

# setup flags
flags="--force --verbose"

export AWS_ACCESS_KEY_ID=$(extract_config "aws_access_key_id")
export AWS_SECRET_ACCESS_KEY=$(extract_config "aws_secret_access_key")

# use the provided region or default to us-east-1
export AWS_REGION=$(extract_config "aws_region")
if [ -z "${AWS_REGION}" ] ; then
  export AWS_REGION="us-east-1"
else
  aws_region="${AWS_REGION}"
fi

env=$(extract_parameter "env")
echo "${env}"

package=$(extract_parameter "package")
if [ -n "${package}" ] ; then
  package=${destination}/${package}
  flags="${flags} --package ${package}"
fi

stage=$(extract_parameter "stage")
if [ -n "${stage}" ] && [ "${stage}" != "null" ] ; then
  flags="${flags} --stage ${stage}"
else
  stage=$(extract_config "stage")
  if [ -n "${stage}" ] && [ "${stage}" != "null" ]; then
    flags="${flags} --stage ${stage}"
  fi
fi

service=$(extract_parameter "service")
if [ -z "${service}" ] || [ "${service}" = "null" ] ; then
  echo "${RED}Service not provided${NC}"
  exit 1 ;
fi

cd $destination/${service}
serverless_cmd $cmd $flags

artifactDirectory=`extract_state "${package}" ".package.artifactDirectoryName"`
version=`basename ${artifactDirectory}`

jq -n "{
  version: {
    stamp: \"${version}\"
  },
  metadata: [
    {
      package: \"${package}\",
      archive: \"${archive}\"
    }
  ]
}" >&3
