#!/bin/sh
set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

. $(dirname $0)/common.sh

export PATH=/usr/local/bin:${PATH}

store_payload

cat ${payload}

cmd="deploy"

# setup flags
flags=

package=$(extract_config "package")
if [ -n "${package}" ] ; then
  package=${destination}/${package}
  flags="${flags} --package ${package}"
fi

stage=$(extract_parameter "stage")
if [ -n "${stage}" ] && [ "${stage}" != "null" ] ; then
  flags="${flags} --stage ${stage}"
else
  stage=$(extract_config "stage")
  if [ -n "${stage}" ] && [ "${stage}" != "null" ]; then
    flags="${flags} --stage ${stage}"
  fi
fi

cd $destination
serverless_cmd $cmd $flags

artifactDirectory=`extract_state "${package}" ".package.artifactDirectoryName"`
version=`basename ${artifactDirectory}`

jq -n "{
  version: {
    stamp: \"${version}\"
  },
  metadata: [
    {
      package: \"${package}\",
      archive: \"${archive}\"
    }
  ]
}" >&3
